[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/']
auto_detect_solc = true
optimizer = true
optimizer_runs = 20000
solc_version = "0.8.0"

# See more config options https://github.com/gakonst/foundry/tree/master/config